apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sound-is-all-you-need-asd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jsk4074/sound_is_all_you_need
    targetRevision: main
    path: helm/dummy-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
